version: '3'

services:

  tomcat-dev:
    build: .
    environment:
      TOMCAT_USERNAME: root
      TOMCAT_PASSWORD: root
    ports:
      - "8888:8080"

  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: npmanager
    volumes:
      - /mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
